image/urls.py
from django.conf.urls import patterns, url
from image import views

urlpatterns = patterns('',
    url(r'^image_browser/$', views.image_browser, name='image_browser'),
    url(r'^image_uploader/$', views.image_uploader, name='image_uploader'),
)

messageapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.post_message, name='post_message'),
	url(r'^posted/$', views.posted, name='posted'),
	url(r'^message.json$', views.update_message, name='update_message'),
	url(r'^page/message.json$', views.update_message, name='update_message_page'),
	url(r'^page/$', views.message_page, name='message_page'),
]

mysite/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    # url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^messageapp/', include('messageapp.urls', namespace='messageapp')),
    url(r'^viewer/', include('viewer.urls', namespace='viewer')),
    url(r'^image/', include('image.urls', namespace='image')),
    url(r'^newsapp/', include('newsapp.urls', namespace='newsapp')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

newsapp/urls.py
from django.conf.urls import url 

from . import views
urlpatterns = [
	url(r'^$', views.show_all_screen, name='show_all_screen' ),
	url(r'^list/$', views.get_all_announce, name='get_all_announce' ),
	# news_page
	url(r'^new/$', views.new_announce, name='new_announce'),
	url(r'^(?P<news_id>\d+)/new/$', views.new_announce, name='new_announce'),
	
	url(r'^to_create_announce/$', views.to_create_announce, name='to_create_announce'),
	#url(r'^to_create_announce/$', views.gotocreatepage, name='to_create_announce'),
	url(r'^(?P<news_id>\d+)/to_create_announce/$', views.to_create_announce, name='to_create_announce'),
	url(r'^(?P<news_id>\d+)/(?P<error_message>\w+)/err_create_announce/$', views.to_create_announce, name='err_create_announce'),
	url(r'^(?P<error_message>\w+)/err_create_announce/$', views.to_create_announce, name='err_create_announce'),

	url(r'^to_create_announce/edit_program.json$', views.edit_program, name='edit_program'),
	url(r'^to_create_announce/edit_text.json$', views.edit_text, name='edit_text'),

	url(r'^to_create_announce/page_to_draft.json$', views.page_to_draft, name='page_to_draft'),  # page_to_draft
	url(r'^delete_page_select.json$', views.delete_page_select, name='delete_page_select'), # delete_page_select
	url(r'^add_new_page.json$', views.add_new_page, name='add_new_page'),# add_new_page
	url(r'^(?P<page_id>\d+)/copy_program/$', views.copy_program, name='copy_program'), # duplicate program
	###########  Add plugin  ###########
	url(r'^(?P<page_id>\d+)/add_text_plugin/$', views.add_text_plugin, name='add_text_plugin'),
	url(r'^(?P<page_id>\d+)/add_image_plugin/$', views.add_image_plugin, name='add_image_plugin'),
	url(r'^(?P<page_id>\d+)/add_pdf_plugin/$', views.add_pdf_plugin, name='add_pdf_plugin'),
	url(r'^(?P<page_id>\d+)/add_video_plugin/$', views.add_video_plugin, name='add_video_plugin'),
	#############  Search  ################
	url(r'^to_search/', views.to_search, name='to_search'),
	url(r'^search_news/', views.search_news, name='search_news'),
	url(r'^pagination_news.json$', views.pagination_news, name='pagination_news'),

	url(r'^create_page/$', views.create_announce_page, name='create_announce_page'),
	url(r'^(?P<news_id>\d+)/delete/$', views.delete_announce, name='delete_announce'),
	#page
	url(r'^(?P<page_id>\d+)/example/$', views.show_example, name='show_example'),
	url(r'^(?P<page_id>\d+)/delete_page/$', views.delete_page, name='delete_page'),
	# screen
	url(r'^(?P<screen_text>\w+)/screen/$', views.screen_announce, name='screen_announce'),
	url(r'^(?P<screen_text>\w+)/(?P<time_text>\w+)/screen/$', views.screen_announce, name='screen_announce'),
	url(r'^(?P<screen_id>\d+)/table/$', views.get_time_table, name='get_time_table'),

	url(r'^(?P<screen_id>\d+)/to_create_screen/$', views.to_create_screen, name='to_create_screen'),
	url(r'^to_create_screen/$', views.to_create_screen, name='to_create_screen'),
	url(r'^(?P<screen_id>\d+)/(?P<error_message>\w+)/err_create_screen/$', views.to_create_screen, name='err_create_screen'),
	url(r'^(?P<error_message>\w+)/err_create_screen/$', views.to_create_screen, name='err_create_screen'),
	
	url(r'^(?P<screen_id>\d+)/create_screen/$', views.create_screen, name='create_screen'),
	url(r'^create_screen/$', views.create_screen, name='create_screen'),
	url(r'^screen/$', views.view_screen, name='view_screen'),
	url(r'^(?P<screen_id>\d+)/delete_screen/$', views.delete_screen, name='delete_screen'),

	url(r'^check_online.json$', views.check_online, name='check_online'),
	url(r'^check_symbol_page.json$', views.check_symbol_page, name='check_symbol_page'),
]

viewer/urls.py
from django.conf.urls import url 

from . import views
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^new/$', views.new, name='new'),

	url(r'^main_page/$', views.main_page, name="main_page"),
	url(r'^to_create_viewer/$', views.to_create_viewer, name="to_create_viewer"),
	url(r'^create_viewer/$', views.create_viewer, name="create_viewer"),
	url(r'^(?P<user_id>\d+)/to_edit_viewer/$', views.to_edit_viewer, name="to_edit_viewer"),
	url(r'^(?P<user_id>\d+)/edit_viewer/$', views.edit_viewer, name="edit_viewer"),
	url(r'^(?P<user_id>\d+)/edit_picture/$', views.edit_picture, name="edit_picture"),
	url(r'^list_viewer/$', views.list_viewer, name="list_viewer"),
	url(r'^(?P<user_id>\d+)/delete_viewer/$', views.delete_viewer, name="delete_viewer"),
	url(r'^search_viewer/$', views.search_viewer, name="search_viewer"),
	url(r'^get_news_by_page/$', views.get_news_by_page, name="get_news_by_page"),
	#url(r'^(?P<news_id>\w+)/(?P<page_c>\w+)/(?P<page_l>\d+)/get_news_by_page/$', views.get_news_by_page, name="get_news_by_page"),
	url(r'^(?P<tag>\w+)/click_tag_news/$', views.click_tag_news, name="click_tag_news"),
	url(r'^add_user_csv/$', views.add_user_csv, name='add_user_csv'),
	url(r'^(?P<user_id>\d+)/disallow_user/$', views.disallow_user, name='disallow_user'),
	url(r'^(?P<user_id>\d+)/allow_user/$', views.allow_user, name='allow_user'),
]

viewer/forms.py
#-*- coding: utf-8 -*-
from django import forms

class ViewerForm(forms.Form):
	username = forms.CharField(max_length=30)
	first_name = forms.CharField()
	last_name = forms.CharField()
	password = forms.CharField(max_length=30,widget=forms.PasswordInput()) #render_value=False
	password_confirm = forms.CharField(max_length=30,widget=forms.PasswordInput())

class ViewerEditForm(forms.Form):
	password_old = forms.CharField(max_length=30,widget=forms.PasswordInput()) #render_value=False
	password = forms.CharField(required=False, max_length=30,widget=forms.PasswordInput()) #render_value=False
	password_confirm = forms.CharField(required=False, max_length=30,widget=forms.PasswordInput())

class ViewerPicture(forms.Form):
	ViewerPictureUploader = forms.ImageField()

class UserCSV(forms.Form):
	userUploader = forms.FileField()

viewer/views.py
#-*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views import generic
from datetime import datetime
from django.contrib.auth.models import Permission, User

from datetime import datetime, date, time, timedelta
import datetime, pytz
from .models import UserViewer
from django.contrib.auth.decorators import permission_required, login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ViewerForm, ViewerEditForm, ViewerPicture, UserCSV
from newsapp.models import PageList

@login_required(login_url="login/")
def home(request):
	template = 'index2.html'
	context = main_news()
	context['tag'] = 'all'
	return render(request, template, context)

@login_required(login_url="../login/")
def main_page(request):
	context  = {}
	context['tag'] = 'all'
	if request.user.is_authenticated():
		user = request.user
		viewer = UserViewer.objects.get(user= user) # get UserViewer object
		if viewer.limit_time: 
			if viewer.limit_time <= datetime.datetime.now().date(): # if time up to disallow.
				permission = Permission.objects.get(codename='permission_viewer') # get permission
				user.user_permissions.add(permission) # add permission
				user.save()
		if user.is_active: # login success
			if user.has_perm('viewer.permission_admin'):
				context['is_admin'] = True
			elif user.has_perm('viewer.permission_viewer'): # viewer
				context['is_viewer'] = True
				context['allow_post'] = True
			else:
				context['is_viewer'] = True

		context['viewer'] = viewer
		context.update(main_news())
		return render(request, 'index2.html', context)
	else:
		context = main_news()
		return render(request, 'index2.html', context)

def login(request):
	template = 'index2.html'
	context = main_news()
	context['tag'] = 'all'
	return render(request, template, context)	

def logout(request):
	from django.contrib.auth import logout
	logout(request)
	context = main_news()
	context['tag'] = 'all'
	return render(request, 'index2.html', context)

def new(request): # login username and password
	from django.contrib.auth import authenticate, login
	if request.method == 'POST':
		username = request.POST["username"]
		password = request.POST["password"]
		user = authenticate(username=username, password=password)
	context = {}
	if user is not None:
		if user.is_active: # login success
			login(request, user)
			if user.has_perm('viewer.permission_admin'):
				context['is_admin'] = True
			elif user.has_perm('viewer.permission_viewer'): # viewer
				context['is_viewer'] = True
				context['allow_post'] = True
			else:
				context['is_viewer'] = True
			return HttpResponseRedirect(reverse('viewer:main_page')) # go to main page by change url on browser.
		else: # login failure 
			context['authen'] = 'try again.'
	else : # no have this user.
		context['authen'] = 'username or password is incorrect.'
	return render(request, 'index2.html', context)

@permission_required('viewer.permission_admin')
def to_create_viewer(request): # go to create viewer page.
	return render(request, 'create_viewer.html',{})

@permission_required('viewer.permission_admin')
def create_viewer(request): # create new viewer.
	from django.core.files import File
	context = {}
	template_name = "create_viewer.html"
	if request.method == "POST":
		MyViewerForm = ViewerForm(request.POST, request.FILES) # get form
		if MyViewerForm.is_valid():
			if User.objects.filter(username = MyViewerForm.cleaned_data["username"]): # if this username is used already.
				context["error_message"] = "This username is used already."
				return render(request, template_name, context) # back to create user page.
			password = MyViewerForm.cleaned_data["password"]
			password_confirm = MyViewerForm.cleaned_data["password_confirm"]
			if password == password_confirm and not User.objects.filter(username=MyViewerForm.cleaned_data["username"]): # if username is unique and password and password_confirm are the same. 
				new_user = User.objects.create_user(username=MyViewerForm.cleaned_data["username"],
													first_name=MyViewerForm.cleaned_data["first_name"],
													last_name=MyViewerForm.cleaned_data["last_name"],
													password=password)	
				new_user.save()
				permission = Permission.objects.get(codename='permission_viewer') # get permission
				new_user.user_permissions.add(permission) # add permission
				new_user.save()
				new_viewer = UserViewer(user = new_user)
				
				return HttpResponseRedirect(reverse('viewer:list_viewer')) # return to list viewer.
			else: # return error password wrong with password_confirm
				context["error_message"] = "invalid comfirm password"
		else: # form is invalid
			context["error_message"] = "Please insert valid data."
	return render(request, template_name, context)

@login_required
def to_edit_viewer(request, user_id):  # go to edit viewer page and send old date viewer to fill in form.
	viewer = get_object_or_404(UserViewer, pk=user_id) # get UserViewer object
	context = {}
	user = viewer.user
	if user.is_active: # login success
		if user.has_perm('viewer.permission_admin'):
			context['is_admin'] = True
		elif user.has_perm('viewer.permission_viewer'): # viewer
			context['is_viewer'] = True
			context['allow_post'] = True
		else:
			context['is_viewer'] = True

	context['viewer'] = viewer
	return render(request, "edit_viewer.html", context)

@login_required
def to_edit_user(request, user_id): # not use
	viewer = get_object_or_404(UserViewer, pk=user_id)
	return render(request, "edit_usr.html", {'viewer':viewer})

@login_required
def edit_picture(request, user_id): # change only picture viewer.
	viewer = get_object_or_404(UserViewer, pk=user_id) # get UserViewer object	
	if request.method == "POST":
		MyPictureForm = ViewerPicture(request.POST, request.FILES)
		print("POST picture: "+str(MyPictureForm.is_valid()) )
		if MyPictureForm.is_valid():
			print("hello picture")
			if viewer.picture.name != 'profile/circleprofile.png':
				viewer.picture.delete()
			viewer.picture = MyPictureForm.cleaned_data["ViewerPictureUploader"] #upload new picture
			viewer.save()
	return HttpResponseRedirect(reverse('viewer:to_edit_viewer', kwargs={'user_id':viewer.id})) # back to the edit_viewer page.

@login_required
def edit_viewer(request, user_id): # save new data viewer. viewer can change only password and profile picture.
	from django.contrib.auth.models import User
	context = {}
	template_name = "edit_viewer.html"
	viewer = get_object_or_404(UserViewer, pk=user_id) # get UserViewer object
	user = viewer.user # User object from UserViewer
	if request.method == "POST":
		MyEditForm = ViewerEditForm(request.POST, request.FILES)
		if MyEditForm.is_valid():
			password = MyEditForm.cleaned_data["password"]
			password_confirm = MyEditForm.cleaned_data["password_confirm"]
			if user.check_password(MyEditForm.cleaned_data["password_old"]) and (password == password_confirm): # if insert valid password and insert valid new password.
				viewer.user.set_password(password) # save new password
				user.save()
				viewer.save()
				context['viewer'] = viewer
				if user.is_active: # login success
					if user.has_perm('viewer.permission_admin'):
						context['is_admin'] = True
						return HttpResponseRedirect(reverse('viewer:list_viewer')) # return to list viewer.
					elif user.has_perm('viewer.permission_viewer'): # viewer
						context['is_viewer'] = True
						context['allow_post'] = True
					else:
						context['is_viewer'] = True
				return HttpResponseRedirect(reverse('viewer:main_page'))
			else:
				context["error_message"] = "invalid comfirm password"
		else:
			context["error_message"] = "invalid insert data"
	if user.is_active: # login success
		if user.has_perm('viewer.permission_admin'):
			context['is_admin'] = True
		elif user.has_perm('viewer.permission_viewer'): # viewer
			context['is_viewer'] = True
			context['allow_post'] = True
		else:
			context['is_viewer'] = True
	context['viewer'] = viewer
	return 	render(request, template_name, context)

@permission_required('viewer.permission_admin')
def list_viewer(request): # show list viewer user.
	context = {}
	users = []
	for each_user in UserViewer.objects.all():
		if each_user.user.has_perm('viewer.permission_viewer'):
			users.append({'each_user': each_user,"perm": "no_has_perm"})
		else:
			users.append({'each_user': each_user,"perm": "no_has_perm"})
	return render(request, "list_viewer.html", {"users":UserViewer.objects.all()})

@permission_required('viewer.permission_admin')
def delete_viewer(request, user_id): # delete viewer by id
	from django.contrib.auth.models import User
	viewer = get_object_or_404(UserViewer, pk=user_id)
	if viewer.picture:
		if viewer.picture.name != 'profile/circleprofile.png':
			viewer.picture.delete()
	viewer.user.delete()
	viewer.delete()
	return HttpResponseRedirect(reverse('viewer:list_viewer')) # return to list viewer.

@permission_required('viewer.permission_admin')
def search_viewer(request): # search viewer by username, firstname and lastname
	from django.contrib.auth.models import User
	template_name = "list_viewer.html"
	context = {}
	if request.method == "GET" and request.GET["search_viewer"]:
		search_data = request.GET["search_viewer"] # data search
		if User.objects.filter(username = search_data): # if found by username
			user = User.objects.filter(username = search_data)
			viewer = UserViewer.objects.filter(user= user)
			context['users'] = viewer
		elif User.objects.filter(first_name = search_data):# if found by first_name
			user = User.objects.filter(first_name = search_data)
			viewer = UserViewer.objects.filter(user= user)
			context['users'] = viewer
		elif User.objects.filter(last_name = search_data):# if found by last_name
			user = User.objects.filter(last_name = search_data)

viewer/templates/base_viewer.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Auth Demo</title>
    <!-- Core CSS - Include with every page -->
    <script src = "{% static 'js/jquery-2.2.3.min.js' %}"></script>
    <script src = "{% static 'bootstrap-3.3.6/dist/js/bootstrap.min.js' %}"></script>
    <link href="{% static 'bootstrap-3.3.6/dist/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Announce system</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'viewer:home' %}">home</a></li>
            <li><a href="{% url 'viewer:edit' %}">edit</a></li>
            <li><a href="{% url 'viewer:list_viewer' %}">manage user</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'viewer:logout' %}">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
            {% block content %}
            {% endblock %}
    <!-- Core Scripts - Include with every page -->
    <script src = "{% static 'js/jquery-2.2.3.min.js' %}"></script>
    <script src = "{% static 'bootstrap-3.3.6/dist/js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

viewer/templates/create_viewer.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<title>KMUTNB Engineer's Announcements</title>
<head>
<meta charset='UTF-8'>
<meta http-equiv="pragma" content="no-cache" />
<meta name='description' content="Engineer's annoucement">
<meta name='keywords' content='HTML,CSS,XML,JavaScript'>
<meta name='author' content="KMUTNB's student">
<meta name='viewport' content='width=device-width, initial-scale=1'>
<script type = "text/javascript" src = "{% static "js/jquery-2.2.3.min.js" %}"></script>
<link rel="stylesheet" href="{% static "bootstrap-3.3.6/dist/css/bootstrap.min.css" %}">
<script src="{% static "bootstrap-3.3.6/dist/js/bootstrap.min.js" %}"></script>
<link rel='stylesheet' href="{% static "FrontEnd/w3.css" %}">
<link rel='stylesheet' href="{% static "FrontEnd/w3-theme-black.css" %}">
<link rel='stylesheet' href="{% static "FrontEnd/Roboto.css" %}">
<link rel='stylesheet' href="{% static "FrontEnd/font-awesome/css/font-awesome-min.css" %}">
<link rel='stylesheet' href="{% static "FrontEnd/Font/Pridi-font.css" %}">


</head>
<style>


input[type=searchform] {
    width: 100%;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    background-color: white;
    background-image: url('pic/searchicon.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    
}
html,body,h1,h2,h3,h4,h5,h6 {font-family: 'Roboto', sans-serif}
.w3-sidenav a,.w3-sidenav h4{padding:12px;}
.w3-navbar a{padding-top:12px !important;padding-bottom:12px !important;}
</style>
<body  onload='clearInput()'>
<!-- Navbar -->
<ul class='w3-navbar w3-theme w3-top w3-left-align w3-large w3-bottombar w3-border-red' style='z-index:4;'>
  <li class='w3-opennav w3-right w3-hide-large'>
    <a class='w3-hover-white w3-large w3-theme-l1' href='javascript:void(0)' onclick='sidenav_open()'><i class='fa fa-bars'></i></a>
  </li>
  <li><a href='{% url "viewer:main_page" %}' class='w3-theme-l1'>Home</a></li>

</ul>
  </div>
</div>







<!-- Sidenav for admin -->
<nav class='w3-sidenav w3-collapse w3-theme-l5 w3-animate-left' style='z-index:3;width:250px;margin-top:-20px;height:95%;' id='adminSidenav'>
  <a href='javascript:void(0)' onclick='sidenav_close()' class='w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large' title='close menu'>
    <i class='fa fa-remove'></i>
  </a>
  <h4><b>Menu</b></h4>

  <!--Manage button (only appear on admin's type user login)-->
  <div class='w3-padding'><button onclick="location.href='{% url "newsapp:show_all_screen" %}'" id='Manage-btn' class='w3-btn w3-indigo w3-large' style='width:100%'>Manage Announces<img src="{% static "FrontEnd/pic/cog.png" %}" style='margin-left:10px;width:25px;height:25px'></img></button></div>
    <!--Manage button (only appear on admin's type user login)-->
  <div class='w3-padding'><button onclick="location.href='{% url "viewer:list_viewer" %}'" id='usr-manage-btn' class='w3-btn w3-indigo w3-large' style='width:100%'>Manage Users<img src="{% static "FrontEnd/pic/cog.png" %}" style='margin-left:10px;width:25px;height:25px'></img></button></div>

 <div class='w3-padding'><button data-toggle="modal" data-target="#postModal" id='post-msg-btn' class='w3-btn w3-blue w3-large' style='width:100%'>Post Message</button></div>


  <div >
  <a href='{% url 'newsapp:to_search' %}' class='w3-right-align w3-hover-black w3-padding w3-section'><i class='fa fa-search'></i>Advance search </a>
  </div>
<!--logout button-->
  <a id='Logout-btn' class='w3-btn w3-red w3-large w3-padding w3-section' style='float:right' href="{% url 'viewer:logout' %}">Logout</a>

</nav>



<!-- Overlay effect when opening sidenav on small screens -->
<div class='w3-overlay w3-hide-large' onclick='sidenav_close()' style='cursor:pointer' title='close side menu' id='myOverlay'></div>

<!-- Main content: shift it to the right by 250 pixels when the sidenav is visible -->
<div class='w3-main' style='margin-left:250px'>
  <div class='w3-row-padding' style='margin-top:70px'>
    
  </div>

<h3 class="w3-text-green " style="margin-left:20px">Add new user</h3>

{% if error_message %}
  <div class="w3-panel w3-deep-orange">
  <span onclick="this.parentElement.style.display='none'" class="w3-closebtn">&times;</span>
    <h4>Warning!</h4>
    <p>{{error_message}}</p>
  </div> 
{% endif %}
<!--new user form-->
<form role="form" method="post" action="{% url 'viewer:create_viewer' %}">
{% csrf_token %}
<h4 style="margin-left:20px">Username</h4>

<input name="username" type="text" class="w3-xmedium w3-section" style="width:30%;margin-left:20px;min-width:200px"></br>
<!---->
<h4 style="margin-left:20px">Firstname</h4>

<input name="first_name" type="text" class="w3-xmedium w3-section" style="width:30%;margin-left:20px;min-width:200px"></br>
<!---->
<h4 style="margin-left:20px">Lastname</h4>

<input name="last_name" type="text" class="w3-xmedium w3-section" style="width:30%;margin-left:20px;min-width:200px"></br>
<!---->
<h4 style="margin-left:20px">Password</h4>

<input name="password" type="password" class="w3-xmedium w3-section" style="width:30%;margin-left:20px;min-width:200px"></br>
<!---->
<h4 style="margin-left:20px">Confirm Password</h4>

<input name="password_confirm" type="password" class="w3-xmedium w3-section" style="width:30%;margin-left:20px;min-width:200px"></br>

<button class="w3-btn w3-xxmedium w3-blue w3-section" style="margin-left:20px">Create user</button>
</form>


<!-- END MAIN -->
</div>

  <!-- Modal post message -->
  <div id="postModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

    <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Post message</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
          <form action="{% url 'messageapp:posted' %}" method="post">
            {% csrf_token %}
            <label for="email">message:</label>
            <input type="text" class="form-control" id="email">
          </div>
        </div>
        <div class="modal-footer">
          <button name="post_button" type="submit" id="" class="btn btn-success">Post</button>
          </form>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

  </div>
  </div>

<script>

function clearInput(){
    $('input[name=last_name]').val('');
    $('input[name=password]').val('');
}

// Script to open and close the sidenav
function sidenav_open() {
    document.getElementById('adminSidenav').style.display = 'block';
    document.getElementById('myOverlay').style.display = 'block';
}
function sidenav_close() {
    document.getElementById('adminSidenav').style.display = 'none';
    document.getElementById('myOverlay').style.display = 'none';
}

</script>

</body>
</html>

viewer/templates/home.html
{% extends 'base_viewer.html' %}

{% block content %}
<div class="container">
<div class="row">

<div class="jumbotron">
  <h1>Hello</h1>
  <p>You are on your Dashboard</p>
</div>
</div>
</div>
{% endblock %}