image/urls.py
from django.conf.urls import patterns, url
from image import views

urlpatterns = patterns('',
    url(r'^image_browser/$', views.image_browser, name='image_browser'),
    url(r'^image_uploader/$', views.image_uploader, name='image_uploader'),
)

mysite/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    # url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^messageapp/', include('messageapp.urls', namespace='messageapp')),
    url(r'^viewer/', include('viewer.urls', namespace='viewer')),
    url(r'^image/', include('image.urls', namespace='image')),
    url(r'^newsapp/', include('newsapp.urls', namespace='newsapp')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

newsapp/urls.py
from django.conf.urls import url 

from . import views
urlpatterns = [
	url(r'^$', views.show_all_screen, name='show_all_screen' ),
	url(r'^list/$', views.get_all_announce, name='get_all_announce' ),
	# news_page
	url(r'^new/$', views.new_announce, name='new_announce'),
	url(r'^(?P<news_id>\d+)/new/$', views.new_announce, name='new_announce'),
	
	url(r'^to_create_announce/$', views.to_create_announce, name='to_create_announce'),
	#url(r'^to_create_announce/$', views.gotocreatepage, name='to_create_announce'),
	url(r'^(?P<news_id>\d+)/to_create_announce/$', views.to_create_announce, name='to_create_announce'),
	url(r'^(?P<news_id>\d+)/(?P<error_message>\w+)/err_create_announce/$', views.to_create_announce, name='err_create_announce'),
	url(r'^(?P<error_message>\w+)/err_create_announce/$', views.to_create_announce, name='err_create_announce'),

	url(r'^to_create_announce/edit_program.json$', views.edit_program, name='edit_program'),
	url(r'^to_create_announce/edit_text.json$', views.edit_text, name='edit_text'),

	url(r'^to_create_announce/page_to_draft.json$', views.page_to_draft, name='page_to_draft'),  # page_to_draft
	url(r'^delete_page_select.json$', views.delete_page_select, name='delete_page_select'), # delete_page_select
	url(r'^add_new_page.json$', views.add_new_page, name='add_new_page'),# add_new_page
	url(r'^(?P<page_id>\d+)/copy_program/$', views.copy_program, name='copy_program'), # duplicate program
	###########  Add plugin  ###########
	url(r'^(?P<page_id>\d+)/add_text_plugin/$', views.add_text_plugin, name='add_text_plugin'),
	url(r'^(?P<page_id>\d+)/add_image_plugin/$', views.add_image_plugin, name='add_image_plugin'),
	url(r'^(?P<page_id>\d+)/add_pdf_plugin/$', views.add_pdf_plugin, name='add_pdf_plugin'),
	url(r'^(?P<page_id>\d+)/add_video_plugin/$', views.add_video_plugin, name='add_video_plugin'),
	#############  Search  ################
	url(r'^to_search/', views.to_search, name='to_search'),
	url(r'^search_news/', views.search_news, name='search_news'),
	url(r'^pagination_news.json$', views.pagination_news, name='pagination_news'),

	url(r'^create_page/$', views.create_announce_page, name='create_announce_page'),
	url(r'^(?P<news_id>\d+)/delete/$', views.delete_announce, name='delete_announce'),
	#page
	url(r'^(?P<page_id>\d+)/example/$', views.show_example, name='show_example'),
	url(r'^(?P<page_id>\d+)/delete_page/$', views.delete_page, name='delete_page'),
	# screen
	url(r'^(?P<screen_text>\w+)/screen/$', views.screen_announce, name='screen_announce'),
	url(r'^(?P<screen_text>\w+)/(?P<time_text>\w+)/screen/$', views.screen_announce, name='screen_announce'),
	url(r'^(?P<screen_id>\d+)/table/$', views.get_time_table, name='get_time_table'),

	url(r'^(?P<screen_id>\d+)/to_create_screen/$', views.to_create_screen, name='to_create_screen'),
	url(r'^to_create_screen/$', views.to_create_screen, name='to_create_screen'),
	url(r'^(?P<screen_id>\d+)/(?P<error_message>\w+)/err_create_screen/$', views.to_create_screen, name='err_create_screen'),
	url(r'^(?P<error_message>\w+)/err_create_screen/$', views.to_create_screen, name='err_create_screen'),
	
	url(r'^(?P<screen_id>\d+)/create_screen/$', views.create_screen, name='create_screen'),
	url(r'^create_screen/$', views.create_screen, name='create_screen'),
	url(r'^screen/$', views.view_screen, name='view_screen'),
	url(r'^(?P<screen_id>\d+)/delete_screen/$', views.delete_screen, name='delete_screen'),

	url(r'^check_online.json$', views.check_online, name='check_online'),
	url(r'^check_symbol_page.json$', views.check_symbol_page, name='check_symbol_page'),
]

viewer/urls.py
from django.conf.urls import url 

from . import views
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^new/$', views.new, name='new'),

	url(r'^main_page/$', views.main_page, name="main_page"),
	url(r'^to_create_viewer/$', views.to_create_viewer, name="to_create_viewer"),
	url(r'^create_viewer/$', views.create_viewer, name="create_viewer"),
	url(r'^(?P<user_id>\d+)/to_edit_viewer/$', views.to_edit_viewer, name="to_edit_viewer"),
	url(r'^(?P<user_id>\d+)/edit_viewer/$', views.edit_viewer, name="edit_viewer"),
	url(r'^(?P<user_id>\d+)/edit_picture/$', views.edit_picture, name="edit_picture"),
	url(r'^list_viewer/$', views.list_viewer, name="list_viewer"),
	url(r'^(?P<user_id>\d+)/delete_viewer/$', views.delete_viewer, name="delete_viewer"),
	url(r'^search_viewer/$', views.search_viewer, name="search_viewer"),
	url(r'^get_news_by_page/$', views.get_news_by_page, name="get_news_by_page"),
	#url(r'^(?P<news_id>\w+)/(?P<page_c>\w+)/(?P<page_l>\d+)/get_news_by_page/$', views.get_news_by_page, name="get_news_by_page"),
	url(r'^(?P<tag>\w+)/click_tag_news/$', views.click_tag_news, name="click_tag_news"),
	url(r'^add_user_csv/$', views.add_user_csv, name='add_user_csv'),
	url(r'^(?P<user_id>\d+)/disallow_user/$', views.disallow_user, name='disallow_user'),
	url(r'^(?P<user_id>\d+)/allow_user/$', views.allow_user, name='allow_user'),
]

newsapp/forms.py
#-*- coding: utf-8 -*-
from django import forms

class ImagefileForm(forms.Form):
	ImageUploader = forms.ImageField() 

class PDFfileForm(forms.Form):
	pdfUploader = forms.FileField()

class VideofileForm(forms.Form):
	VideoUploader = forms.FileField()

class VideoURLForm(forms.Form):
	inputVideoURL = forms.CharField(max_length=200, required=False)

class SearchNewsForm(forms.Form):
	search_name = forms.CharField(max_length=100, required=False)
	begin_date = forms.CharField(max_length=100, required=False)
	begin_time = forms.CharField(max_length=100, required=False)
	end_date = forms.CharField(max_length=100, required=False)
	end_time = forms.CharField(max_length=100, required=False)
	search_screen = forms.CharField(max_length=100, required=False)
	tag1 = forms.BooleanField(required=False)
	tag2 = forms.BooleanField(required=False)
	tag3 = forms.BooleanField(required=False)
	tag4 = forms.BooleanField(required=False)

newsapp/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.utils.timezone import localtime 
import json
from datetime import datetime, date, time, timedelta
import datetime, pytz

from .models import NewsPage, Screen, PageList
from .forms import ImagefileForm, PDFfileForm, VideofileForm, SearchNewsForm, VideoURLForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cms.models.pagemodel import Page

from viewer.models import UserViewer
from django.contrib.auth.decorators import permission_required, login_required, user_passes_test
from django.utils.decorators import method_decorator

NEWSAPP_ERROR_CHOICES = [
	'This name is used already.',
	'start_time is repeatedly with anathor.',
	'end_time is repeatedly with anathor.',
	'start_time is more than end_time.',
	'start_time is equal end_time.'
]

@permission_required('viewer.permission_admin')
@login_required
def show_all_screen(request):
	""" show a big picture that what program is showed in each screen. 
	but for simple show only status on or off.(still connect with server)"""
	template_name = 'newsapp/status_screen.html'
	context = {}
	#context['screens'] = get_list_screen
	program_list = []
	for screen in get_list_screen():
		context_p = {}
		programs = NewsPage.objects.filter(screen=screen, publish=True)
		if len(programs) > 1: # if find more than 1 publish program
			for program in programs: # find only 1 publish program
				if program.was_published(): # check if be publish.
					context_p['program'] = program
					if PageList.objects.filter(program=program):
						context_p['page'] = PageList.objects.filter(program=program)[0] # get only first page for show picture.
					else:
						context_p['page'] = False
					break # stop this loop
				else:
					context_p['program'] = False
					context_p['page'] = False
		elif len(programs) == 1: # find 1 publish program
			if programs[0].was_published():
				context_p['program'] = programs[0] 
				if PageList.objects.filter(program=programs[0]):
					context_p['page'] = PageList.objects.filter(program=programs[0])[0] # get only first page for show picture.
				else:
					context_p['page'] = False
			else:
				context_p['program'] = False
				context_p['page'] = False
		else: # if no have publish program
			context_p['program'] = False
			context_p['page'] = False
		context_p['screen'] = screen
		program_list.append(context_p)
	context['data_screen'] = program_list
	return render(request, template_name, context)

@permission_required('viewer.permission_admin')
@login_required
def get_all_announce(request):
	""" get list of announce."""
	template_name = 'newsapp/programs.html'
	all_news = []
	all_screen  = get_list_screen()
	for news in get_list_news():
		all_news.append(news)
	return render(request, template_name, {'all_news': all_news, 'all_screen': all_screen})
# temperal chanal to create page
@permission_required('viewer.permission_admin')
@login_required
def gotocreatepage(request):
	return render(request, 'newsapp/create.html', {})

@permission_required('viewer.permission_admin')
@login_required
def to_create_announce(request, news_id = None, error_message=None): 
	"""if no news_id send data to choose in create page.
	   if get news_id send date to choose in create page and send old data 
	to fill in each field form.
	"""
	from cms.api import create_page # use cms api
	from django.core.files import File
	template_name = 'newsapp/create.html'
	screens = get_list_screen() # send screens list for selection
	
	if news_id == None:
		new_program = NewsPage() # create new program
		first_page = PageList()  # create first page for new program
		new_program.save()
		first_page.program = new_program # first is sub page of new_program
		first_page.index = 0  # first page has index 0.
		first_page.save()

		web_page = create_page('web_page' + str(first_page.id), 'news.html', 'en') # create page
		web_page.publish('en')
		first_page.page = web_page # connect real page with first_page
		first_page.url = web_page.get_public_url('en')  + '?edit_off'
		first_page.save()
		first_page.name = 'page'+str(first_page.id)
		first_page.save()
		
		filename = 'empty_page.png'	# file name
		filepath = 'media/media/page_preview/empty_page.png'    # file path 
		with open(filepath, 'rb') as f:	# create empty page to be preview page 
			file_obj = File(f, name=filename)
			first_page.picture.save(str(first_page.name) + '.png', file_obj) # rename file following by PageList.name and set PageList.preview
			first_page.save()

		context = {'program':new_program, 'list_page':[first_page], 'all_screen':screens} # list_page will be list because forloop useing in create.html
		return HttpResponseRedirect(reverse('newsapp:to_create_announce', 
				kwargs= {'news_id':new_program.id} ))
	else: # edit program then get data's program to fill in create.html
		program_geten = get_object_or_404(NewsPage ,pk=news_id)
		# code belog one line that was commented is old list_page.
		#list_page = PageList.objects.filter(program=program_geten).order_by('index') # get all PageList in this program and sort them by index.
		# start check has_edit
		from djangocms_text_ckeditor.models import Text
		list_page = []
		pages = PageList.objects.filter(program=program_geten).order_by('index') # get all page
		for web_page in pages:
			placeholders = list(web_page.page.get_placeholders())
			if placeholders[0].get_plugins_list():
				plugins = placeholders[0].get_plugins_list()[0]
				instance, plugin = plugins.get_plugin_instance() # get plugin class
				if type(instance) is Text: # if this page has Text plugin
					list_page.append({'web_page':web_page, 'has_edit':True}) # set has edit = True
				else: # if not be Text plugin
					list_page.append({'web_page':web_page, 'has_edit':False}) # set has edit = False
			else:
				list_page.append({'web_page':web_page, 'has_edit':False}) # set has edit = False
		# end check has_edit
		context = {'program':program_geten, 
				   'list_page':list_page, 
				   'all_screen':screens,
				   'news_screen':program_geten.screen.name if program_geten.screen != None else '',
				   'news_start_date':program_geten.start_time.strftime("%d-%m-%Y") if program_geten.start_time != None else '', 
				   'news_start_time':( program_geten.start_time+datetime.timedelta(hours=7) ).strftime("%H:%M") if program_geten.start_time != None else '',
				   #'news_end_date':program_geten.end_time.strftime("%d-%m-%Y") if program_geten.end_time != None else '',
				   'news_end_time':(program_geten.end_time+datetime.timedelta(hours=7) ).strftime("%H:%M") if program_geten.end_time != None else '',
				   }
	
	return render(request, template_name, context)

@permission_required('viewer.permission_admin')
@login_required
def new_announce(request, news_id = None):
	""" create new announce.
	send error message in those case.
	1. name is repeatedly with anathor.
	2. start_time and end_time are repeatedly with anathor.
	3. send start_time or end_time back to page for warn that these time
	are not suitable.
	"""
	from datetime import datetime, date, time
	if news_id == None:
		news_page = NewsPage()
	else:
		news_page = get_object_or_404(NewsPage, pk=news_id)
	start_datetime, end_datetime = '', '' # use for send to check error.
	if request.method == 'POST':
		if request.POST['announce_name']:
			news_page.name = request.POST['announce_name']
		if request.POST['screen'] and request.POST['screen'] != "":
			screen_geten = Screen.objects.get(name = request.POST['screen'])
			news_page.screen = screen_geten
		if request.POST['news_page']:
			page_geten = request.POST['news_page']
			target_page = news_page.my_get_title_page(page_geten)
			news_page.page = target_page
		if request.POST['announce_start_date'] and request.POST['announce_start_time']:
			start_date = request.POST['announce_start_date'].split('-') # 
			start_date = [ int(i) for i in start_date ] # convert to int list
			start_time = request.POST['announce_start_time'].split(':')
			start_time = [ int(i) for i in start_time ] # convert to int list
			
			start_date = date(start_date[2], start_date[1], start_date[0])
			start_time = time(start_time[0], start_time[1])
			start_datetime = datetime.combine(start_date, start_time)
			news_page.start_time = start_datetime
		if request.POST['announce_end_date'] and request.POST['announce_end_time']:
			end_date = request.POST['announce_end_date'].split('-') # 
			end_date = [ int(i) for i in end_date ] # convert to int list
			end_time = request.POST['announce_end_time'].split(':')
			end_time = [ int(i) for i in end_time ] # convert to int list

			end_date = date(end_date[2], end_date[1], end_date[0])
			end_time = time(end_time[0], end_time[1])
			end_datetime = datetime.combine(end_date, end_time)
			news_page.end_time = end_datetime
		# NewsPage's name should not repeatedly with any NewsPage object.
		# start_time and end_time should not repeatedly with anathor NewsPage object.
		# send error messsage if screen name is repeadly with anathor.
		context = check_error_announce(request.POST['announce_name'], start_datetime, end_datetime, request.POST['screen'], news_id)
		if context != 0:
			return HttpResponseRedirect(reverse('newsapp:err_create_announce', 
				kwargs=context))	
		news_page.save()
	return HttpResponseRedirect(reverse('newsapp:get_all_announce'))

def check_error_announce(announce_name, start_datetime, end_datetime, screen_name, news_id = None ):
	utc = pytz.utc # get tzinfo UTC
	start_datetime = start_datetime.replace(tzinfo=utc) - timedelta(hours=7) # set tzinfo to be UTC
	end_datetime = end_datetime.replace(tzinfo=utc) - timedelta(hours=7)
	print(start_datetime)
	print(end_datetime)
	err = []
	set_screen = Screen.objects.get(name=screen_name)
	print(set_screen)

newsapp/templates/newsapp/example.html
{% load staticfiles %}
{% block content %}
<script type = "text/javascript" src = "{% static "js/jquery-2.2.3.min.js" %}"></script>
<script src="{% static "js/newsapp-jquery.js" %}"></script>

	<h1>example page</h1>
	<div class="{{example_mark}}">
	{{example_content}}
	</div>
{% endblock content %}

newsapp/templates/newsapp/list_pageOLD.html
<h1>List Page</h1>

{% regroup all_page by page_name as page_name_list %}
<ul>
	{% for page_name in page_name_list %}
	 	<li>{{ page_name.grouper }}
	 	<ul>
	 		{% for item in page_name.list %}
	 		{% ifequal forloop.counter 1 %}
	 			<li>{{ item.page_name }}</li>
	 			<a href="{{item.draft_url}}" target="_blank"> edit page</a>
  				<a href="{% url 'newsapp:show_example' item.id %}" > view example</a>
  				<a href="{% url 'newsapp:delete_page' item.id %}">delete</a>
  			{% endifequal %}
  			{% endfor %}
	 	</ul>
		</li>
	{% endfor %}
</ul>
<a href="{% url 'newsapp:to_create_page' %}" target="_blank"> create page</a>
<br><br>
<a href="{% url 'newsapp:show_all_screen' %}">screen status</a><br>
<a href="{% url 'newsapp:get_all_announce' %}">news</a><br>
<a href="{% url 'newsapp:show_all_page' %}">page</a><br>
<a href="{% url 'newsapp:view_screen' %}">screen</a><br>
<a href="{% url 'newsapp:get_time_table' %}">Time table</a><br>

newsapp/templates/newsapp/pagemodalOLD.html
<h1>Create Page</h1>

<form action="{% url 'newsapp:create_announce_page' %}" method="post">
  {% csrf_token %}
  Title:<br>
  <input type="text" name="page_title">
  <br>
  <input type="submit" value="save">
  <a href="{% url 'newsapp:show_all_screen' %}">Cancel</a>
</form>

newsapp/templates/newsapp/table.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Create news Program</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type = "text/javascript" src = "{% static "js/jquery-2.2.3.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "bootstrap-3.3.6/dist/css/bootstrap.min.css" %}">
    <script src="{% static "bootstrap-3.3.6/dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/table-jquery.js" %}"></script>
	<link rel='stylesheet' href="{% static "FrontEnd/w3.css" %}">
	<link rel='stylesheet' href="{% static "FrontEnd/w3-theme-black.css" %}">
	<link rel='stylesheet' href="{% static "FrontEnd/Roboto.css" %}">
	<link rel='stylesheet' href="{% static "FrontEnd/font-awesome/css/font-awesome-min.css" %}">
	<link rel='stylesheet' href="{% static "FrontEnd/Font/Pridi-font.css" %}">
  </head>
<style>
input[type=searchform] {
    width: 100%;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    background-color: white;
    background-image: url('pic/searchicon.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
}
html,body,h1,h2,h3,h4,h5,h6 {font-family: 'Roboto', sans-serif}
.w3-sidenav a,.w3-sidenav h4{padding:12px;}
.w3-navbar a{padding-top:12px !important;padding-bottom:12px !important;}
</style>
<body>

<!-- Navbar -->
<ul class='w3-navbar w3-theme w3-top w3-left-align w3-large w3-bottombar w3-border-red' style='z-index:4;'>
  <li class='w3-opennav w3-right w3-hide-large'>
    <a class='w3-hover-white w3-large w3-theme-l1' href='javascript:void(0)' onclick='w3_open()'><i class='fa fa-bars'></i></a>
  </li>
  <li><a href="{% url 'viewer:main_page' %}">Home</a></li>
  <li><a href='#' class='w3-theme-l1'> --> Time table</a></li>
</ul>


<!-- Sidenav -->
<nav class='w3-sidenav w3-collapse w3-theme-l5 w3-animate-left' style='z-index:3;width:250px;margin-top:-20px' id='mySidenav'>
  <a href='javascript:void(0)' onclick='w3_close()' class='w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large' title='close menu'>
    <i class='fa fa-remove'></i>
  </a>

  <!--Manage button (only appear on admin's type user login)-->
<div style='margin-top:50px;text-align: center;'><button style="height: 80px" class='w3-btn w3-orange w3-xlarge w3-round-large w3-section' onclick="location.href='{% url 'newsapp:to_create_announce' %}'">New program</button></div>
  <div style='margin-top:10px;text-align: center;'><a href="{% url 'newsapp:show_all_screen' %}" class=' w3-hover-black  w3-large'>Screen status</a></div>
  <div style='text-align: center;'><a href="{% url 'newsapp:get_all_announce' %}" class=' w3-dark-grey w3-hover-black w3-large'>Programs</a></div>
  <div style='text-align: center;'><a href="{% url 'newsapp:view_screen' %}" class=' w3-hover-black w3-large'>Screens</a></div>

  <div >

<!--login button-->
  <a class="w3-btn w3-red w3-large w3-section" style="float:right" href="{% url 'viewer:logout' %}">Logout</a>
</nav>


<!-- Overlay effect when opening sidenav on small screens -->
<div class='w3-overlay w3-hide-large' onclick='w3_close()' style='cursor:pointer' title='close side menu' id='myOverlay'></div>

<!-- Main content: shift it to the right by 250 pixels when the sidenav is visible -->
<div class='w3-main' style='margin-left:250px'>
  <div class='w3-row-padding' style='margin-top:70px'>
    
  </div>
  <header class='w3-container'>



    <!--Tags select-->
  </header>


  <div id='announce' >
    <!-- First Grid-->

  </div>


  <!-- Pagination -->


<!-- END MAIN -->
</div>

<script>
// Script to open and close the sidenav
function w3_open() {
    document.getElementById('mySidenav').style.display = 'block';
    document.getElementById('myOverlay').style.display = 'block';
}
 
function w3_close() {
    document.getElementById('mySidenav').style.display = 'none';
    document.getElementById('myOverlay').style.display = 'none';
}
</script>

<div class="container-fluid">
	<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-10">
			<h3>Time table page</h3>

			<table class="table table-striped" >
				<thead>
					<tr>
						<th>Program name</th>
						<th>start time</th>
						<th>end time</th>
						<th>screen</th>
						<th>menu</th>
					</tr>
				</thead>
				{% for news in table_news %}
					<tr>
						<td><a href="{% url 'newsapp:to_create_announce' news.id %}">{{news.name}}</a></td>
						<td>{{news.start_time}}</td>
						<td>{{news.end_time}}</td>
						<td>{{news.screen}}</td>
						<td>
							<a href="{% url 'newsapp:to_create_announce' news.id %}" style="color:#003366;"><span class="glyphicon glyphicon-pencil"></span> edit</a> 
							<a href="#" id="{{news.name}}" onclick="TargetSelect(this, {{news.id}})" style="color:#333333;"><span class="glyphicon glyphicon-duplicate"></span> copy </a>
							<a href="#" data-toggle="modal" data-target="#deleteModal{{news.id}}" style="color:#b51212;"><span class="glyphicon glyphicon-remove"></span> delete </a>
						</td>
					</tr>

					<!-- Modal delete program -->
					<div id="deleteModal{{news.id}}" class="modal fade" role="dialog">
					  <div class="modal-dialog">

					    <!-- Modal content-->
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title">delete program</h4>
					      </div>
					      <div class="modal-body">
					        <p>Are you sure want to delete this program.</p>
					      </div>
					      <div class="modal-footer">
					        <a href="{% url 'newsapp:delete_announce' news.id %}" name="delete_button" type="button" id="" class="btn btn-danger">delete</a>
					        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					      </div>
					    </div>

					  </div>
					</div>

					<!-- Modal copy program -->
					<div id="copyModal{{news.id}}" class="modal fade" role="dialog">
					  <div class="modal-dialog">

					    <!-- Modal content-->
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title">copy program</h4>
					      </div>
					      <div class="modal-body">
							<div class="form-group">
  								<label for="usr">Program name:</label>
  						      <form name="CopyProgram" action="{% url 'newsapp:copy_program' news.id %}" method="post">
						      {% csrf_token %}
  								<input name="copy_name" type="text" class="form-control" required="Please fill some content.">
							</div>
							{% if error_message %}
								<p style="color:red">{{error_message}}</p>
							{% endif %}
					      </div>
					      <div class="modal-footer">
					        <button name="duplicate_button" type="submit" class="btn btn-success">Duplicate</a>
					        </form>
					        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					      </div>
					    </div>

					  </div>
					</div>
				{% endfor %}
				
			</table>
		</div>
	</div>
</div>
{% if id_error %}
	<script>
		var err_modal = '#copyModal'+ '{{id_error}}';
		$(err_modal).modal();
	</script>
{% endif %}
</body>
</html>