image/urls.py
from django.conf.urls import patterns, url
from image import views

urlpatterns = patterns('',
    url(r'^image_browser/$', views.image_browser, name='image_browser'),
    url(r'^image_uploader/$', views.image_uploader, name='image_uploader'),
)

mysite/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    # url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^messageapp/', include('messageapp.urls', namespace='messageapp')),
    url(r'^viewer/', include('viewer.urls', namespace='viewer')),
    url(r'^image/', include('image.urls', namespace='image')),
    url(r'^newsapp/', include('newsapp.urls', namespace='newsapp')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

viewer/urls.py
from django.conf.urls import url 

from . import views
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^new/$', views.new, name='new'),

	url(r'^main_page/$', views.main_page, name="main_page"),
	url(r'^to_create_viewer/$', views.to_create_viewer, name="to_create_viewer"),
	url(r'^create_viewer/$', views.create_viewer, name="create_viewer"),
	url(r'^(?P<user_id>\d+)/to_edit_viewer/$', views.to_edit_viewer, name="to_edit_viewer"),
	url(r'^(?P<user_id>\d+)/edit_viewer/$', views.edit_viewer, name="edit_viewer"),
	url(r'^(?P<user_id>\d+)/edit_picture/$', views.edit_picture, name="edit_picture"),
	url(r'^list_viewer/$', views.list_viewer, name="list_viewer"),
	url(r'^(?P<user_id>\d+)/delete_viewer/$', views.delete_viewer, name="delete_viewer"),
	url(r'^search_viewer/$', views.search_viewer, name="search_viewer"),
	url(r'^get_news_by_page/$', views.get_news_by_page, name="get_news_by_page"),
	#url(r'^(?P<news_id>\w+)/(?P<page_c>\w+)/(?P<page_l>\d+)/get_news_by_page/$', views.get_news_by_page, name="get_news_by_page"),
	url(r'^(?P<tag>\w+)/click_tag_news/$', views.click_tag_news, name="click_tag_news"),
	url(r'^add_user_csv/$', views.add_user_csv, name='add_user_csv'),
	url(r'^(?P<user_id>\d+)/disallow_user/$', views.disallow_user, name='disallow_user'),
	url(r'^(?P<user_id>\d+)/allow_user/$', views.allow_user, name='allow_user'),
]

viewer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.
class UserViewer(models.Model):  
    user = models.OneToOneField(User)  
    picture = models.ImageField(null=True, blank=True, upload_to= 'profile', default='profile/circleprofile.png')
    limit_time = models.DateField(null=True, blank=True, default=None)
    class Meta:
        permissions = (
            ('permission_viewer', 'Search news read news and post message'),
            ('permission_admin', 'manage user and news program'),
        )

    def __str__(self):  
          return "%s's profile" % self.user  

def create_user_profile(sender, instance, created, **kwargs):  
    if created:  
       profile, created = UserViewer.objects.get_or_create(user=instance)  

post_save.connect(create_user_profile, sender=User) 

viewer/forms.py
#-*- coding: utf-8 -*-
from django import forms

class ViewerForm(forms.Form):
	username = forms.CharField(max_length=30)
	first_name = forms.CharField()
	last_name = forms.CharField()
	password = forms.CharField(max_length=30,widget=forms.PasswordInput()) #render_value=False
	password_confirm = forms.CharField(max_length=30,widget=forms.PasswordInput())

class ViewerEditForm(forms.Form):
	password_old = forms.CharField(max_length=30,widget=forms.PasswordInput()) #render_value=False
	password = forms.CharField(required=False, max_length=30,widget=forms.PasswordInput()) #render_value=False
	password_confirm = forms.CharField(required=False, max_length=30,widget=forms.PasswordInput())

class ViewerPicture(forms.Form):
	ViewerPictureUploader = forms.ImageField()

class UserCSV(forms.Form):
	userUploader = forms.FileField()

viewer/views.py
#-*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views import generic
from datetime import datetime
from django.contrib.auth.models import Permission, User

from datetime import datetime, date, time, timedelta
import datetime, pytz
from .models import UserViewer
from django.contrib.auth.decorators import permission_required, login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ViewerForm, ViewerEditForm, ViewerPicture, UserCSV
from newsapp.models import PageList

@login_required(login_url="login/")
def home(request):
	template = 'index2.html'
	context = main_news()
	context['tag'] = 'all'
	return render(request, template, context)

@login_required(login_url="../login/")
def main_page(request):
	context  = {}
	context['tag'] = 'all'
	if request.user.is_authenticated():
		user = request.user
		viewer = UserViewer.objects.get(user= user) # get UserViewer object
		if viewer.limit_time: 
			if viewer.limit_time <= datetime.datetime.now().date(): # if time up to disallow.
				permission = Permission.objects.get(codename='permission_viewer') # get permission
				user.user_permissions.add(permission) # add permission
				user.save()
		if user.is_active: # login success
			if user.has_perm('viewer.permission_admin'):
				context['is_admin'] = True
			elif user.has_perm('viewer.permission_viewer'): # viewer
				context['is_viewer'] = True
				context['allow_post'] = True
			else:
				context['is_viewer'] = True

		context['viewer'] = viewer
		context.update(main_news())
		return render(request, 'index2.html', context)
	else:
		context = main_news()
		return render(request, 'index2.html', context)

def login(request):
	template = 'index2.html'
	context = main_news()
	context['tag'] = 'all'
	return render(request, template, context)	

def logout(request):
	from django.contrib.auth import logout
	logout(request)
	context = main_news()
	context['tag'] = 'all'
	return render(request, 'index2.html', context)

def new(request): # login username and password
	from django.contrib.auth import authenticate, login
	if request.method == 'POST':
		username = request.POST["username"]
		password = request.POST["password"]
		user = authenticate(username=username, password=password)
	context = {}
	if user is not None:
		if user.is_active: # login success
			login(request, user)
			if user.has_perm('viewer.permission_admin'):
				context['is_admin'] = True
			elif user.has_perm('viewer.permission_viewer'): # viewer
				context['is_viewer'] = True
				context['allow_post'] = True
			else:
				context['is_viewer'] = True
			return HttpResponseRedirect(reverse('viewer:main_page')) # go to main page by change url on browser.
		else: # login failure 
			context['authen'] = 'try again.'
	else : # no have this user.
		context['authen'] = 'username or password is incorrect.'
	return render(request, 'index2.html', context)

@permission_required('viewer.permission_admin')
def to_create_viewer(request): # go to create viewer page.
	return render(request, 'create_viewer.html',{})

@permission_required('viewer.permission_admin')
def create_viewer(request): # create new viewer.
	from django.core.files import File
	context = {}
	template_name = "create_viewer.html"
	if request.method == "POST":
		MyViewerForm = ViewerForm(request.POST, request.FILES) # get form
		if MyViewerForm.is_valid():
			if User.objects.filter(username = MyViewerForm.cleaned_data["username"]): # if this username is used already.
				context["error_message"] = "This username is used already."
				return render(request, template_name, context) # back to create user page.
			password = MyViewerForm.cleaned_data["password"]
			password_confirm = MyViewerForm.cleaned_data["password_confirm"]
			if password == password_confirm and not User.objects.filter(username=MyViewerForm.cleaned_data["username"]): # if username is unique and password and password_confirm are the same. 
				new_user = User.objects.create_user(username=MyViewerForm.cleaned_data["username"],
													first_name=MyViewerForm.cleaned_data["first_name"],
													last_name=MyViewerForm.cleaned_data["last_name"],
													password=password)	
				new_user.save()
				permission = Permission.objects.get(codename='permission_viewer') # get permission
				new_user.user_permissions.add(permission) # add permission
				new_user.save()
				new_viewer = UserViewer(user = new_user)
				
				return HttpResponseRedirect(reverse('viewer:list_viewer')) # return to list viewer.
			else: # return error password wrong with password_confirm
				context["error_message"] = "invalid comfirm password"
		else: # form is invalid
			context["error_message"] = "Please insert valid data."
	return render(request, template_name, context)

@login_required
def to_edit_viewer(request, user_id):  # go to edit viewer page and send old date viewer to fill in form.
	viewer = get_object_or_404(UserViewer, pk=user_id) # get UserViewer object
	context = {}
	user = viewer.user
	if user.is_active: # login success
		if user.has_perm('viewer.permission_admin'):
			context['is_admin'] = True
		elif user.has_perm('viewer.permission_viewer'): # viewer
			context['is_viewer'] = True
			context['allow_post'] = True
		else:
			context['is_viewer'] = True

	context['viewer'] = viewer
	return render(request, "edit_viewer.html", context)

@login_required
def to_edit_user(request, user_id): # not use
	viewer = get_object_or_404(UserViewer, pk=user_id)
	return render(request, "edit_usr.html", {'viewer':viewer})

@login_required
def edit_picture(request, user_id): # change only picture viewer.
	viewer = get_object_or_404(UserViewer, pk=user_id) # get UserViewer object	
	if request.method == "POST":
		MyPictureForm = ViewerPicture(request.POST, request.FILES)
		print("POST picture: "+str(MyPictureForm.is_valid()) )
		if MyPictureForm.is_valid():
			print("hello picture")
			if viewer.picture.name != 'profile/circleprofile.png':
				viewer.picture.delete()
			viewer.picture = MyPictureForm.cleaned_data["ViewerPictureUploader"] #upload new picture
			viewer.save()
	return HttpResponseRedirect(reverse('viewer:to_edit_viewer', kwargs={'user_id':viewer.id})) # back to the edit_viewer page.

@login_required
def edit_viewer(request, user_id): # save new data viewer. viewer can change only password and profile picture.
	from django.contrib.auth.models import User
	context = {}
	template_name = "edit_viewer.html"
	viewer = get_object_or_404(UserViewer, pk=user_id) # get UserViewer object
	user = viewer.user # User object from UserViewer
	if request.method == "POST":
		MyEditForm = ViewerEditForm(request.POST, request.FILES)
		if MyEditForm.is_valid():
			password = MyEditForm.cleaned_data["password"]
			password_confirm = MyEditForm.cleaned_data["password_confirm"]
			if user.check_password(MyEditForm.cleaned_data["password_old"]) and (password == password_confirm): # if insert valid password and insert valid new password.
				viewer.user.set_password(password) # save new password
				user.save()
				viewer.save()
				context['viewer'] = viewer
				if user.is_active: # login success
					if user.has_perm('viewer.permission_admin'):
						context['is_admin'] = True
						return HttpResponseRedirect(reverse('viewer:list_viewer')) # return to list viewer.
					elif user.has_perm('viewer.permission_viewer'): # viewer
						context['is_viewer'] = True
						context['allow_post'] = True
					else:
						context['is_viewer'] = True
				return HttpResponseRedirect(reverse('viewer:main_page'))
			else:
				context["error_message"] = "invalid comfirm password"
		else:
			context["error_message"] = "invalid insert data"
	if user.is_active: # login success
		if user.has_perm('viewer.permission_admin'):
			context['is_admin'] = True
		elif user.has_perm('viewer.permission_viewer'): # viewer
			context['is_viewer'] = True
			context['allow_post'] = True
		else:
			context['is_viewer'] = True
	context['viewer'] = viewer
	return 	render(request, template_name, context)

@permission_required('viewer.permission_admin')
def list_viewer(request): # show list viewer user.
	context = {}
	users = []
	for each_user in UserViewer.objects.all():
		if each_user.user.has_perm('viewer.permission_viewer'):
			users.append({'each_user': each_user,"perm": "no_has_perm"})
		else:
			users.append({'each_user': each_user,"perm": "no_has_perm"})
	return render(request, "list_viewer.html", {"users":UserViewer.objects.all()})

@permission_required('viewer.permission_admin')
def delete_viewer(request, user_id): # delete viewer by id
	from django.contrib.auth.models import User
	viewer = get_object_or_404(UserViewer, pk=user_id)
	if viewer.picture:
		if viewer.picture.name != 'profile/circleprofile.png':
			viewer.picture.delete()
	viewer.user.delete()
	viewer.delete()
	return HttpResponseRedirect(reverse('viewer:list_viewer')) # return to list viewer.

@permission_required('viewer.permission_admin')
def search_viewer(request): # search viewer by username, firstname and lastname
	from django.contrib.auth.models import User
	template_name = "list_viewer.html"
	context = {}
	if request.method == "GET" and request.GET["search_viewer"]:
		search_data = request.GET["search_viewer"] # data search
		if User.objects.filter(username = search_data): # if found by username
			user = User.objects.filter(username = search_data)
			viewer = UserViewer.objects.filter(user= user)
			context['users'] = viewer
		elif User.objects.filter(first_name = search_data):# if found by first_name
			user = User.objects.filter(first_name = search_data)
			viewer = UserViewer.objects.filter(user= user)
			context['users'] = viewer
		elif User.objects.filter(last_name = search_data):# if found by last_name
			user = User.objects.filter(last_name = search_data)

viewer/templates/not_use/create_viewer2.html
{% extends 'base_viewer.html' %}

{% block content %}

 <form role="form" method="post" action="{% url 'viewer:create_viewer' %}" >
 {% csrf_token %}
<div class="form-group">
  <label for="usr">Userame:</label>
  <input name="username" type="text" class="form-control" id="usr">
</div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input name="password" type="password" class="form-control" id="pwd">
  </div>
  <div class="form-group">
    <label for="pwd">Password_confirm:</label>
    <input name="password_confirm" type="password" class="form-control" id="pwd">
  </div>
  <div class="form-group">
    <label for="usr">Firstname:</label>
    <input name="first_name" type="text" class="form-control" id="usr">
  </div>

  <div class="form-group">
    <label for="usr">Lastname:</label>
    <input name="last_name" type="text" class="form-control" id="usr">
  </div>

  <button type="submit" class="btn btn-default">Submit</button>
</form>
  <a href="{% url 'viewer:list_viewer' %}" class="btn btn-default">Cancel</a>

{% if error_message %}
  <p>{{error_message}}</p>
{% endif %}
{% endblock %}

viewer/templates/not_use/edit_usr.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<title>KMUTNB Engineer's Announcements</title>
<head>
<meta charset='UTF-8'>
<meta name='description' content="Engineer's annoucement">
<meta name='keywords' content='HTML,CSS,XML,JavaScript'>
<meta name='author' content="KMUTNB's student">
<meta name='viewport' content='width=device-width, initial-scale=1'>
<script type = "text/javascript" src = "{% static "js/jquery-2.2.3.min.js" %}"></script>
<link rel="stylesheet" href="{% static "bootstrap-3.3.6/dist/css/bootstrap.min.css" %}">
<script src="{% static "bootstrap-3.3.6/dist/js/bootstrap.min.js" %}"></script>
<link rel='stylesheet' href="{% static "FrontEnd/w3.css" %}">
<link rel='stylesheet' href="{% static "FrontEnd/w3-theme-black.css" %}">
<link rel='stylesheet' href="{% static "FrontEnd/Roboto.css" %}">
<link rel='stylesheet' href="{% static "FrontEnd/font-awesome/css/font-awesome-min.css" %}">
<link rel='stylesheet' href="{% static "FrontEnd/Font/Pridi-font.css" %}">


</head>
<style>


input[type=searchform] {
    width: 100%;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    background-color: white;
    background-image: url('pic/searchicon.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    
}
html,body,h1,h2,h3,h4,h5,h6 {font-family: 'Roboto', sans-serif}
.w3-sidenav a,.w3-sidenav h4{padding:12px;}
.w3-navbar a{padding-top:12px !important;padding-bottom:12px !important;}
</style>
<body  onload='changepages(1)'>
<!-- Navbar -->
<ul class='w3-navbar w3-theme w3-top w3-left-align w3-large w3-bottombar w3-border-red' style='z-index:4;'>
  <li class='w3-opennav w3-right w3-hide-large'>
    <a class='w3-hover-white w3-large w3-theme-l1' href='javascript:void(0)' onclick='sidenav_open()'><i class='fa fa-bars'></i></a>
  </li>
  <li><a href='#' class='w3-theme-l1' onclick='changepages(1)'>Home</a></li>

</ul>


<!--login modal-->
<div id='IDlogin' class='w3-modal'>
  <div class='w3-modal-content w3-card-8 w3-animate-zoom' style='max-width:600px'>
    <div class='w3-center'><br>
      <span onclick="document.getElementById('IDlogin').style.display='none';document.getElementById('mySidenav').style.display='block';" class='w3-closebtn w3-hover-black w3-container w3-padding-8 w3-display-topright' title='Close Modal'>&times;</span>
      <img src='pic/KMUTNB-LOGO.jpg' alt='Avatar' style='width:30%' class='w3-circle w3-margin-top'>
    </div>

    <!-- login form -->

    <form class='w3-container' method='POST' action='index2.html'>
      <div class='w3-section'>
        <label><b>Username</b></label>
        <input class='w3-input w3-border w3-margin-bottom' type='text' placeholder='Enter Username' name='usrname' required>
        <label><b>Password</b></label>
        <input class='w3-input w3-border' type='password' placeholder='Enter Password' name='psw' required>
        <button class='w3-btn-block w3-green w3-section w3-padding' type='submit'>Login</button>
        
      </div>
    </form>
    <!-- forgot password ?-->
    <div class='w3-container w3-border-top w3-padding-16 w3-light-grey'>
      <span class='w3-padding w3-hide-small'>Forgot <a href='#'>password?</a></span>
      <button onclick="document.getElementById('IDlogin').style.display='none';document.getElementById('mySidenav').style.display='block'" type='button' class='w3-btn w3-red w3-right'>Cancel</button>
      
    </div>

  </div>
</div>







<!-- Sidenav for admin -->
<nav class='w3-sidenav w3-collapse w3-theme-l5 w3-animate-left' style='z-index:3;width:250px;margin-top:-20px;height:95%;' id='adminSidenav'>
  <a href='javascript:void(0)' onclick='sidenav_close()' class='w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large' title='close menu'>
    <i class='fa fa-remove'></i>
  </a>
  <h4><b>Menu</b></h4>
  

  <!--Manage button (only appear on admin's type user login)-->
  <div class='w3-padding'><button id='Manage-btn' class='w3-btn w3-indigo w3-large' style='width:100%'>Manage Announces<img src='{% static "FrontEnd/pic/cog.png" %}' style='margin-left:10px;width:25px;height:25px'></img></button></div>
    <!--Manage button (only appear on admin's type user login)-->
  <div class='w3-padding'><button id='usr-manage-btn' class='w3-btn w3-indigo w3-large' style='width:100%'>Manage Users<img src='{% static "FrontEnd/pic/cog.png" %}' style='float:right;width:25px;height:25px'></img></button></div>

  <div class='w3-padding'><button id='post-msg-btn' class='w3-btn w3-blue w3-large' style='width:100%'>Post Message</button></div>


  <div >
  <a href='search.html' class='w3-right-align w3-hover-black w3-padding w3-section'><i class='fa fa-search'></i>Advance search </a>
  </div>
<!--logout button-->
  <button id='Logout-btn' class='w3-btn w3-red w3-large w3-padding w3-section' style='float:right'>Logout</button>

</nav>









<!-- Overlay effect when opening sidenav on small screens -->
<div class='w3-overlay w3-hide-large' onclick='sidenav_close()' style='cursor:pointer' title='close side menu' id='myOverlay'></div>

<!-- Main content: shift it to the right by 250 pixels when the sidenav is visible -->
<div class='w3-main' style='margin-left:250px'>
  <div class='w3-row-padding' style='margin-top:70px'>
    
  </div>
<div style="width:240px">
<h1 class="w3-center w3-text-green w3-border w3-border-green" style="margin-left:20px">Edit user info</h1>
</div>

<h2 style="margin-left:20px">Avatar</h2>
<!--VVVVVVVV copy content from edit account  VVVVVVVV-->
<img style="margin-left:20px" src='{{viewer.picture.url}}'>


<!--text field for each info-->

<h2 style="margin-left:20px">Username</h2>
<!---->{{viewer.user.username}}
<h2 style="margin-left:20px">Firstname</h2>
<!---->{{viewer.user.firstname}}
<h2 style="margin-left:20px">Lastname</h2>
<!---->{{viewer.user.lastname}}

<form>
<input class="w3-xlarge w3-section" style="width:30%;margin-left:20px;min-width:200px"></br>
<button class="w3-btn w3-xxlarge w3-blue w3-section" style="margin-left:20px">Change Password</button>
<button class="w3-btn w3-xlarge w3-red w3-section" style="margin-left:30%">cancel</button>
</form>



<!-- END MAIN -->
</div>

<script>




// Script to open and close the sidenav
function sidenav_open() {
    document.getElementById('adminSidenav').style.display = 'block';
    document.getElementById('myOverlay').style.display = 'block';
}
function sidenav_close() {
    document.getElementById('adminSidenav').style.display = 'none';
    document.getElementById('myOverlay').style.display = 'none';
}
//

document.getElementById("Manage-btn").onclick = function () {
        location.href = "manage.html";
    };

document.getElementById("usr-manage-btn").onclick = function () {
        location.href = "usr_manage.html";
    };
document.getElementById("Logout-btn").onclick = function () {
        location.href = "index2.html";
};

</script>

</body>
</html>

viewer/templates/not_use/list_viewer2.html
{% extends 'base_viewer.html' %}

{% block content %}
  <a href="{% url 'viewer:to_create_viewer' %}" class="btn btn-default">NEW USER</a><br>

 <form role="form" method="get" action="{% url 'viewer:search_viewer' %}" >
 {% csrf_token %}
<div class="form-group">
  <label for="usr">Search:</label>
  <input name="search_viewer" type="text" class="form-control" id="usr">
</div>
  <button type="submit" class="btn btn-default">Search</button>
</form><br><br>

{% if error_message %}
  <p>{{error_message}}</p>
{% endif %}

<ul>
{% for user in users %}
  <li>
    <p><strong>Username: </strong>{{user.user.username}}</p>
    <p><strong>Firstname: </strong>{{user.user.first_name}}</p>
    <p><strong>Lastname: </strong>{{user.user.last_name}}</p>
    <a href="{% url 'viewer:to_edit_viewer' user.id %}">edit</a>
    <a href="{% url 'viewer:delete_viewer' user.id %}">delete</a>
  </li>
{% endfor %}
</ul>

{% endblock %}